# Generated by Django 3.2.4 on 2021-06-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('ClassRoom_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ClassRoom_Name', models.CharField(max_length=10)),
                ('ClassRoom_Capacity', models.IntegerField()),
                ('Teaching_Building', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=2)),
                ('capacity', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArrangeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_beg', models.IntegerField()),
                ('Course_end', models.IntegerField()),
                ('ClassRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.classroom')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.course')),
            ],
        ),
    ]
