# Generated by Django 3.2.4 on 2021-06-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangeResult',
            fields=[
                ('Course_Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ClassRoom_Id', models.IntegerField(unique=True)),
                ('Course_beg', models.IntegerField()),
                ('Course_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('ClassRoom_Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ClassRoom_Name', models.CharField(max_length=10)),
                ('ClassRoom_Capacity', models.IntegerField()),
                ('Teaching_Building', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Course_Name', models.CharField(max_length=10)),
                ('Course_term', models.IntegerField()),
                ('Course_year', models.IntegerField()),
                ('Teacher_Id', models.IntegerField(unique=True)),
                ('Course_Capacity', models.IntegerField()),
                ('Course_Range', models.IntegerField()),
            ],
        ),
    ]
