# Generated by Django 3.2.4 on 2021-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('ClassRoom_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('ClassRoom_Name', models.CharField(max_length=10)),
                ('ClassRoom_Capacity', models.IntegerField()),
                ('Teaching_Building', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=10)),
            ],
        ),
    ]
